### ISSUE TITLE
GRAPH= is undefined

### ISSUE THREAD

**Issue by phoe** [kraison/graph-utils#1]
I expected to find the function `graph=` but it does not seem to be defined.

**Comment by kraison** [comment]
Ah yes, the method name is actually graph-equal. So the graph-utils package has an incorrect export. I can't fix it at the moment, as I am traveling with no laptop. In the meantime, you can update the graph-utils package in your local copy to export graph-equal. Make a pull request if you like, otherwise I'll fix this in the next few days.
